npmScopes:
  ants:
    npmPublishRegistry: https://npm.pkg.github.com

packageExtensions:
  "@jest/core@*":
    peerDependencies:
      ts-node: "*"
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.0"
      "#supports-color": "npm:supports-color@9.2.2"
  jest-cli@*:
    peerDependencies:
      ts-node: "*"
  jest@*:
    peerDependencies:
      ts-node: "*"
    peerDependenciesMeta:
      ts-node:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
