org: jujulego
app: ants
service: ants-api
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  data-table: 'ants-data-${sls:stage}'

  esbuild:
    bundle: true
    minify: false

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-3

  tracing:
    lambda: true
    apiGateway: true

  environment:
    DATA_TABLE_NAME: ${self:custom.data-table}

  httpApi:
    cors:
      allowedOrigins:
        - https://jujulego.github.io

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchGetItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt DataTable.Arn
            - !Sub '${DataTable.Arn}/index/*'

  tags:
    Project: ants

  stackTags:
    Project: ants

functions:
  listTileMaps:
    handler: src/tile-maps/handlers.list
    events:
      - httpApi:
          path: /api/tile-maps
          method: get

  getTileMap:
    handler: src/tile-maps/handlers.getById
    events:
      - httpApi:
          path: /api/tile-maps/{id}
          method: get

resources:
  Resources:
    DataTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.data-table}
        AttributeDefinitions:
          - AttributeName: table
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: table
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: table-index
            Projection:
              ProjectionType: KEYS_ONLY
            KeySchema:
              - AttributeName: table
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
