org: jujulego
app: ants
service: ants-api
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  data-table: 'ants-data-${sls:stage}'

  esbuild:
    bundle: true
    minify: false

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-3
  deploymentMethod: direct

  tracing:
    lambda: true
    apiGateway: true

  environment:
    DATA_TABLE_NAME: ${self:custom.data-table}

  httpApi:
    cors:
      allowedOrigins:
        - https://jujulego.github.io

    authorizers:
      cognito:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !Sub 'https://cognito-idp.eu-west-3.amazonaws.com/${UserPool}'
        audience:
          - !Ref UserPoolClient

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchGetItem
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt DataTable.Arn
            - !Sub '${DataTable.Arn}/index/*'

  tags:
    Project: ants

  stackTags:
    Project: ants

functions:
  listTileMaps:
    handler: src/tile-maps/handlers.list
    events:
      - httpApi:
          path: /api/tile-maps
          method: get
          authorizer:
            name: cognito

  getTileMap:
    handler: src/tile-maps/handlers.getById
    events:
      - httpApi:
          path: /api/tile-maps/{id}
          method: get
          authorizer:
            name: cognito

resources:
  Resources:
    UserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: 'ants-user-pool-${sls:stage}'
        AutoVerifiedAttributes:
          - email
        UsernameAttributes:
          - email
        UsernameConfiguration:
          CaseSensitive: false

    UserPoolClient:
      Type: 'AWS::Cognito::UserPoolClient'
      Properties:
        ClientName: 'ants-frontend-${sls:stage}'
        UserPoolId: !Ref UserPool
        CallbackURLs:
          - http://localhost:3000
          - https://jujulego.github.io
        GenerateSecret: false
        SupportedIdentityProviders:
          - COGNITO
        AllowedOAuthFlows:
          - implicit
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - email
          - openid
          - profile
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH

    UserPoolDomain:
      Type: 'AWS::Cognito::UserPoolDomain'
      Properties:
        Domain: 'ants-${sls:stage}'
        UserPoolId: !Ref UserPool

    DataTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.data-table}
        AttributeDefinitions:
          - AttributeName: table
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: table
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: table-index
            Projection:
              ProjectionType: KEYS_ONLY
            KeySchema:
              - AttributeName: table
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
